import Header from '@/components/Header';
import Footer from '@/components/Footer';
// import { SessionProvider } from "next-auth/react";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <SessionProvider>
      <html lang="en">
        <body className="bg-gray-100">
          <Header />
          <main className="min-h-screen flex justify-center items-center">{children}</main>
          <Footer />
        </body>
      </html>
    // </SessionProvider>
  );
}
